---
driver:
  name: vagrant
  gui: false
  customize:
    cpus: 2
    memory: 4096
  ssh:
    pty: true

provisioner:
  name: chef_zero
  # You many wish to test your CHEF::Log.<level> messages while using test-kitchen.  Change the below
  # value to the level of choice.  For cleaner output, comment this option out.
  # log_level: info
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: occm
    run_list:
      - recipe[netapp_ontap_cloud::occm_setup]
    verifier:
      inspec_tests:
        - test/smoke/occm
    attributes:
      occm:
        user:
        company_name: 'Exosphere'
        install_pkg: true
  - name: ontap_aws
    run_list:
      - recipe[netapp_ontap_cloud::occm_install]
      - recipe[netapp_ontap_cloud::ontap_cloud_aws_standalone]
    verifier:
      inspec_tests:
        - test/smoke/occm
    attributes:
      occm:
        user:
        company_name: 'Exosphere'
        install_pkg: true
      ontap_cloud:
        ontap:
          standalone:
            name: 'demolab'


